name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick graphicsmagick

    - uses: actions/checkout@v3

    - name: Use Node.js v14
      uses: actions/setup-node@v3
      with:
        node-version: '14.x'

    - run: npm install --dev

    - run: npm test
